### ISSUE TITLE
The lonely table

### ISSUE THREAD

**Issue by Karyum** [WebAhead7/blogit#10]
I'm not raising this issue cause there is 1 table only, I'm raising it cause the table is badly named
https://github.com/WebAhead7/blogit/blob/main/database/init.sql#L4

what does `ourdata` mean to you, cause for me not much.

also add more tables so you can practice using `JOINS`

**Comment by mjmajadly** [comment]
![giphy](https://user-images.githubusercontent.com/43019810/99653199-69ca6c00-2a61-11eb-8b5d-4cc5f6905f78.gif)

**Comment by mjmajadly** [comment]
We changed the name: 
![ssss](https://user-images.githubusercontent.com/43019810/99654088-84511500-2a62-11eb-8443-a8a6c8fb987d.PNG)

Unfortunately, we did not have the time to do more tables as we were learning by doing.
