### ISSUE TITLE
I hacked your form 

### ISSUE THREAD

**Issue by alaabashiyi** [WebAhead7/blogit#11]
html validation isn't enough, you also need to validate the sent data in the backend as well.
![image](https://user-images.githubusercontent.com/29834132/99649325-c0817700-2a5c-11eb-98a6-4700e6405dbd.png)

**Comment by mjmajadly** [comment]
no you didnt. we have this code:      
 INSERT INTO ourdata(username, myname, post) VALUES($1,$2,$3)`,
    values

which should prevent injections
