### ISSUE TITLE
sql data base default 

### ISSUE THREAD

**Issue by nuwrss** [WebAhead7/blogit#5]
the data base shouldnt have nay default data 
INSERT INTO ourdata (username, myname, post) VALUES
  ('Sery1976', 'Serya', 'This is my FIRST blog, testttt1'),
  ('Notne1991', 'Nathan', 'This is my SECOND blog, testttt2'),
  ('Moull1990', 'Molly', 'This is my THIRD blog, testttt3'),
  ('Spont1935', 'Spartin', 'This is my FOURTH blog, testttt4'),
  ('Precand', 'Tracy', 'This is my FIFTH blog, testttt5')
;

**Comment by mjmajadly** [comment]
Deleting default values, it was more for testing (will push updated files when done with issues)
