### ISSUE TITLE
Homepage handler

### ISSUE THREAD

**Issue by alaabashiyi** [WebAhead7/blogit#8]
https://blogitkav.herokuapp.com/public/index.html 

it should not show index.html, looks like when clicking the image in the homepage it anchers to index.html

its better to stay https://blogitkav.herokuapp.com/, e3ne navigate to "/" instead of "public/index.html"

**Comment by mjmajadly** [comment]
Issue fixed, changed from    <a href="/public/index.html"> to       <a href="/">
