### ISSUE TITLE
files managment

### ISSUE THREAD

**Issue by alaabashiyi** [WebAhead7/blogit#9]
there is no file management in /public folder, all the html ,css, JS are floating around. 
it should be organised.

**Comment by Karyum** [comment]
also a lot of file are badly named, like `submit.js` and `client.js`

**Comment by mjmajadly** [comment]
> also a lot of file are badly named, like `submit.js` and `client.js`

We dont have client.js file. Why the rest badly names? 'submit' is for submitting the form. 'data' to get the data from the table/database

**Comment by mjmajadly** [comment]
> there is no file management in /public folder, all the html ,css, JS are floating around.
> it should be organised.

No. I think its good the way we have them. Everything is organized by name (index html/css/js) etc. 
they are not floating around, they are listed under each other which should make it easier for the user/programmer to see what is going on
